apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parquet-pvc 
spec:
# facing this bug - https://github.com/Azure/AKS/issues/223
#  storageClassName: azurefile-csi-premium
#  accessModes:
#    - ReadWriteMany
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
